apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployfd9
  labels:
    app: autodeployfd9
  namespace: demoappfromgithub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployfd9
  template:
    metadata:
      labels:
        app: autodeployfd9
    spec:
      containers:
        - name: autodeployfd9
          image: acrworkflow1714087647040.azurecr.io/image-workflow-1714087647040:latest
          ports:
            - containerPort: 5000