apiVersion: v1
kind: Service
metadata:
  name: autodeployfd9
  namespace: demoappfromgithub
spec:
  type: LoadBalancer
  selector:
    app: autodeployfd9
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000